[package]
name = "egui_commonmark"
authors = ["Erlend Walstad"]
version = "0.7.4"
edition = "2021"
description = "Commonmark viewer for egui"
keywords = ["commonmark", "egui"]
categories = ["gui"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/lampsitter/egui_commonmark"
documentation = "https://docs.rs/egui_commonmark"
include = ["src/*.rs", "LICENSE-MIT", "LICENSE-APACHE", "Cargo.toml"]

[dependencies]
egui = { git = "https://github.com/emilk/egui", rev = "8003e6b" }
pulldown-cmark = { version = "0.9.3", default-features = false }

syntect = { version = "5.0.0", optional = true, default-features = false, features = [
    "default-fancy",
] }

document-features = { version = "0.2", optional = true }

[features]
## Syntax highlighting for code blocks
syntax_highlighting = ["syntect"]

[dev-dependencies]
eframe = { git = "https://github.com/emilk/egui", rev = "8003e6b" }
egui_extras = { git = "https://github.com/emilk/egui", rev = "8003e6b", features = [
    "all-loaders",
    "log",
] }
image = { version = "0.24", default-features = false, features = ["png"] }

[package.metadata.docs.rs]
# docs.rs build can fail with the fetch feature enabled
features = ["syntax_highlighting", "svg", "document-features"]
